src/src/com/czina/cdidemo/cdi/ApplicationBean.java
package com.czina.cdidemo.cdi;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.slf4j.Logger;

import com.czina.cdidemo.cdi.api.BeanInfo;

@ApplicationScoped
@Named("applicationBean")
public class ApplicationBean extends BeanInfo {

	@Inject
	private Logger logger;

	private String savedState;

	@Inject
	private SessionBean sessionBean;

	public String getSavedState() {
		return savedState;
	}

	public void setSavedState(String savedState) {
		this.savedState = savedState;
	}

	public String getSessionContent() {
		return this.sessionBean.getSessionText();
	}

}

src/src/com/czina/cdidemo/cdi/SessionBean.java
package com.czina.cdidemo.cdi;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;

import org.slf4j.Logger;

import com.czina.cdidemo.cdi.api.BeanInfo;

@SessionScoped
public class SessionBean extends BeanInfo implements Serializable {

	private static final long serialVersionUID = 2968899012586733763L;

	@Inject
	private Logger logger;

	private String sessionText;

	public String getSessionText() {
		return sessionText;
	}

	public void setSessionText(String sessionText) {
		logger.info("Set sessionText to new value: {}", sessionText);
		this.sessionText = sessionText;
	}

}

src/src/com/czina/cdidemo/cdi/api/QualifiedBean.java
package com.czina.cdidemo.cdi.api;

public abstract class QualifiedBean {
	
	public String getName() {
		return this.getClass().getSimpleName();
	}

}

src/src/com/czina/cdidemo/cdi/decorator/TestDecoratorBean.java
package com.czina.cdidemo.cdi.decorator;

import javax.decorator.Decorator;
import javax.decorator.Delegate;
import javax.enterprise.inject.Any;
import javax.inject.Inject;

import org.slf4j.Logger;

import com.czina.cdidemo.cdi.api.Decorable;

@Decorator
public abstract class TestDecoratorBean implements Decorable {

	@Inject
	private Logger logger;
	
	@Inject @Delegate @Any
	private Decorable delegating;
	
	@Override
	public void doSomething(String input) {
		logger.info("I'm delegating invocation (parameter: {})", input);
	}

	
}

src/src/com/czina/cdidemo/ui/BeanInfoBean.java
package com.czina.cdidemo.ui;

import java.util.ArrayList;
import java.util.List;

import javax.enterprise.inject.Any;
import javax.enterprise.inject.Instance;
import javax.enterprise.inject.Model;
import javax.inject.Inject;
import javax.inject.Named;

import org.slf4j.Logger;

import com.czina.cdidemo.cdi.api.BeanInfo;

@Model
@Named("beanInfoBean")
public class BeanInfoBean {

	@Inject
	private Logger logger;

	@Inject
	@Any
	private Instance<BeanInfo> beanInfoInstances;

	private List<BeanInfo> beanInfoList;

	public Instance<BeanInfo> getBeanInfoInstances() {
		return beanInfoInstances;
	}

	public List<BeanInfo> getBeanInfoList() {
		beanInfoList = new ArrayList<BeanInfo>();
		for (BeanInfo beanInfo : beanInfoInstances) {
			beanInfoList.add(beanInfo);
		}
		return beanInfoList;
	}

}

src/src/com/czina/cdidemo/ui/EnterBean.java
package com.czina.cdidemo.ui;

import javax.enterprise.inject.Model;
import javax.inject.Inject;
import javax.inject.Named;

import org.slf4j.Logger;

import com.czina.cdidemo.cdi.ApplicationBean;
import com.czina.cdidemo.cdi.SessionBean;

@Model
@Named("enterBean")
public class EnterBean {

	@Inject
	private Logger logger;

	@Inject
	private SessionBean sessionBean;

	@Inject
	private ApplicationBean applicationBean;

	public String getSessionText() {
		return sessionBean.getSessionText();
	}

	public void setSessionText(String value) {
		sessionBean.setSessionText(value);
	}

	public String getApplicationText() {
		return applicationBean.getSavedState();
	}

	public void setApplicationText(String value) {
		applicationBean.setSavedState(value);
	}

	public void save() {
		logger.info("Save index page");
	}
}

src/src/com/czina/cdidemo/ui/TerminalController.java
package com.czina.cdidemo.ui;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Any;
import javax.enterprise.inject.Instance;
import javax.enterprise.inject.UnsatisfiedResolutionException;
import javax.inject.Inject;
import javax.inject.Named;

import org.slf4j.Logger;

import com.czina.cdidemo.cdi.command.CmdAnnotationInstance;
import com.czina.cdidemo.cdi.command.Command;

@ApplicationScoped
@Named("terminalController")
public class TerminalController {
	
	@Inject
	private Logger logger;

	@Inject
	@Any
	private Instance<Command> commandInstance;

	public String handleCommand(String command, String[] params) {
		StringBuffer output = new StringBuffer();

		try {
		Command commandBean = commandInstance.select(
				new CmdAnnotationInstance(command)).get();
		output.append(commandBean.handleCommand(command, params));
		} catch(UnsatisfiedResolutionException e) {
			output.append("SYNTAX ERROR: ").append(e.getMessage());
			logger.error("SYNTAX ERROR!", e);
		}

		return output.toString();
	}
}

src/WebContent/WEB-INF/template/layout.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<h:outputStylesheet name="css/default.css" />
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<title>CDI Demo</title>
</h:head>

<h:body>
	<p:layout id="layout" fullPage="true">
		<p:layoutUnit position="west" width="250">
			<p:menu>
				<p:submenu label="Menu">
					<p:menuitem value="Home" outcome="/index" icon="ui-icon-home" />
					<p:menuitem value="Bean info" outcome="/beanInfo"
						icon="ui-icon-star" />


				</p:submenu>
			</p:menu>
		</p:layoutUnit>
		<p:layoutUnit position="center">
			<ui:insert name="content">
			</ui:insert>
		</p:layoutUnit>
	</p:layout>
</h:body>
</html>

src/WebContent/beanInfo.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:body>
	<ui:composition template="WEB-INF/template/layout.xhtml">
		<ui:define name="content">
			<h1>Bean info page</h1>
			<h:form>
				<p:dataTable var="bean" value="#{beanInfoBean.beanInfoList}">
					<p:column headerText="Bean name">
						<h:outputText value="#{bean.beanName}" />
					</p:column>

					<p:column headerText="Bean id">
						<h:outputText value="#{bean.applicationId}" />
					</p:column>

				</p:dataTable>
			</h:form>
			&nbsp;
			<p:terminal prompt="cdidemo $"
				commandHandler="#{terminalController.handleCommand}" height="480"
				width="640" welcomeMessage="BeanInfo commands" />
		</ui:define>
	</ui:composition>

</h:body>
</html>

src/WebContent/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:body>
	<ui:composition template="WEB-INF/template/layout.xhtml">
		<ui:define name="content">
			<h1>CDI Demo start page</h1>
			<h:form>
				<p:panelGrid columns="2">
					<p:outputLabel value="Application ID:" />
					<p:outputLabel value="#{applicationBean.applicationId}"></p:outputLabel>
					<p:outputLabel value="Application content" />
					<p:inputText value="#{enterBean.applicationText}"></p:inputText>
					<p:outputLabel value="Session content" />
					<p:inputText value="#{enterBean.sessionText}"></p:inputText>
					<p:outputLabel value="" />
					<p:commandButton value="Submit" ajax="false"
						actionListener="#{enterBean.save}" />
				</p:panelGrid>
			</h:form>
		</ui:define>
	</ui:composition>
</h:body>
</html>